suorganizer/blog/urls.py
from django.urls import path,re_path

from .views import Postlist,post_details,PostCreate

urlpatterns = [
    re_path(r"^$" ,Postlist.as_view(),{'parent_template': 'base.html'},name='blog_post_list'),
    re_path(r'^post/create/$',PostCreate.as_view(),name='blog_post_create'),
    re_path(r'^(?P<year>\d{4})/'
            r'(?P<month>\d{1,2})/'
            r'(?P<slug>[\w\-]+)/$',post_details,{'parent_template': 'base.html'},name='blog_post_details'),
    re_path(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
    
] 

suorganizer/organizer/urls.py
from django.urls import path ,re_path

from views import tag_detail,tag_list,TagCreate,startup_details,startup_list,StartUpCreate,CreateNewsLink


urlpatterns = [
    re_path(r"^tag/$",tag_list,name="organizer_tag_list"),
    re_path(r'^tag/create/$',TagCreate.as_view(),name='organizer_tag_create'),
    re_path(r'^tag/(?P<slug>[\w\-]+)/$',tag_detail, name='organizer_tag_detail'),
    re_path(r'^startup/(?P<slug>[\w\-]+)/$',startup_details, name='organizer_startup_detail'),
    re_path(r"^startup/$",startup_list,name='organizer_startup_list'),
    re_path(r'^create/$',StartUpCreate.as_view,name='blog_post_create'),
    re_path(r'^newslink/create/$',CreateNewsLink.as_view(),name='organizer_newslink_create')
    
]

suorganizer/suorganizer/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import views
urlpatterns = [
    re_path(r'^/$',views.redirect_root),
    path('',include('blog.urls')),
    path('',include('organizer.urls')),
    path('admin/', admin.site.urls),
]

suorganizer/organizer/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class  Tag(models.Model):
    name = models.CharField(max_length=31,unique=True)
    slug = models.SlugField(max_length=31,unique=True,help_text='a label for url config')
    def __str__(self):
        return self.name.title()
    
    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('organizer_detail_tag_detail',kwargs={'slug':self.slug})

class  Startup(models.Model):
    name = models.CharField(max_length=31,db_index=True)
    slug = models.SlugField(max_length=31,unique=True,help_text='a label for URL config')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tag = models.ManyToManyField(Tag)
    def __str__(self):
        return self.name()
    
    class meta:
        ordering = ['name']
        get_latest_by = 'founded_date'  # get the latest startup by founded_date

    def get_absolute_url(self):
        return reverse('organizer_startup_detail',
                       kwargs={'slug':self.slug})
    
class  Newslink(models.Model):
    title= models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup,on_delete=models.CASCADE)
    
    def get_absolute_url(self):
        return self.startup.get_absolute_url()
    
    def __str__(self):
        return '{}:{}'.format(self.startup,self.title)
    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'  # get the latest newslink by pub_date

suorganizer/organizer/forms.py
from django import forms
from . models import Tag,Newslink,Startup
from django.core.exceptions import ValidationError
    


class SlugCleanMixing:
    
    def clean_slug(self):
        new_slug =(self.cleaned_data['slug'].lower())
        if new_slug == 'create':
            raise ValidationError( 'Slug may not be "create".')
        return new_slug


class TagForm(SlugCleanMixing,forms.ModelForm):
    
    class Meta:
        model = Tag
        fields = ['name', 'slug']

    def clean_name(self):
        return self.cleaned_data['name'].lower()
    
class NewslinkForm(forms.ModelForm):
    class Meta:
        model = Newslink
        fields = '__all__'

    


class StartUpForm(SlugCleanMixing,forms.ModelForm):
    class Meta:
        model = Startup
        fields = '__all__'  # For all fields, you can also specify a list of

    

suorganizer/organizer/views.py
from django.http.response import HttpResponse
from .models import Tag,Startup
from django.views.generic import View
from django.shortcuts import get_object_or_404,redirect,render
from django.template import Context, loader
from.forms import TagForm,StartUpForm,NewslinkForm


def tag_list(request):
    return render(request,"organizer/tag_list.html",{"tag_list":Tag.objects.all()})



def tag_detail(request,slug):
    tag=get_object_or_404(Tag,slug__iexact=slug)
    template = loader.get_template("organizer/tag_details.html")
    context ={'tag': tag}
    return HttpResponse(template.render(context))


def startup_list(request):
    return render(request,"organizer/startup_list.html",{'startup_list':Startup.objects.all()})

def startup_details(request,slug):
    startup=get_object_or_404(Startup,slug__iexact=slug)
    return render(request,"organizer/startup_detail.html",{'startup':startup})
    

# def tag_create(request):
#     if request.method == 'POST':
#         form=TagForm(request.POST)
#         if form.is_valid():
#             new_tag=form.save()
#             return redirect(new_tag)
        
#     else:
#         form =TagForm()
#         return render(request,"organizer/tag_form.html",{'form':form})



class ObjectCreateMixing:
    form_class=None
    template_name=''

    def get(self,request):
        return render(request,self.template_name,
                      {'form':self.form_class()})
    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            new_object=form.save()
            return redirect(new_object)
        else:
            return render(request,self.template_name,{'form':form})
class TagCreate(ObjectCreateMixing,View):
    form_class=TagForm
    template_name='organizer/tag_form.html'
  
        
class StartUpCreate(ObjectCreateMixing,View):
    form_class=StartUpForm
    template_name='organizer/startup_form.html'    
    


class CreateNewsLink(ObjectCreateMixing,view):
    form_class = NewslinkForm
    template_name = 'organizer/newslink_form'

# class CreateNewsLink(ObjectCreateMixing,View):
#     form_class= NewslinkForm
#     template_name='organizer/newslink_form'
        


# class CreateNewsLink(View):
#     form_class = NewslinkForm
#     template_name='organizer/newslink_form'
#     def get(self,request):
#         return render(request,self.template_name,{'form':self.form_class()})
#     def post(self,request):
#         form= self.form_class(request.POST)
#         if form.is_valid():
#             new_newslink=form.save()
#             return redirect(new_newslink)
#         else:
#             return render(request,self.form_class,{'form':form})

suorganizer/organizer/templates/organizer/base_organiser.html
{% extends parent_template|default:"base.html" %}

suorganizer/organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{%block title%}
{{ block.super }} - Link News Article to Startup
{% endblock %}

{%block content%}
<div></div>
<form action="{url'organizer_newslink_create'}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Link Article</button>
</form>
<div></div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <article>
        <h2>{{startup.name}}</h2>
        <dl>
            <dt>Date Founded</dt>
            <dd>{{startup.founded_date|date:"F js,Y"}}</dd>
            <dt>Website</dt>
            <dd>{{startup.website|urlize}}</dd>
            <!-- <dd><a href="{{startup.website}}">{{startup.website}}</a></dd> -->
            <dt>Contact</dt>
            <dd>
                {{startup.contact}}
            </dd>
            <dt> Tag{{ startup.tags.count|pluralize}}</dt>
            {%for tag in startup.tags.all%}
            <dd><a href="{{tag.get_absolute_url}}">{{tag.name|title}}</a></dd>
            {% endfor%}
        </dl>
        <p>{{startup.description|linebreaks}}</p>
        {% if startup.newslink_set.all%}
        <section>
            <h3>Recent News</h3>
            <div>
                <a href="{%url'organizer_newslink_create'%}">Add Article</a>
            </div>
            <ul>
                {%for newslink in startup.newslink_set.all%}
                <li><a href="{{newslink.title}}">{{newslink.title|title}}</a></li>
                {% endfor %}
            </ul>
        </section>
        {% endif %}
        {% if startup.blog_posts.all%}
        <section>
            <h3>Blog Post{{startup.blog_posts.count|pluralize}}</h3>
            <ul>
                {%for post in startup.blog_posts.all%}
                <li><a href="{{post.get_absolute_url}}">{{post.title|title}}</a></li>
                {%endfor%}
            </ul>
        </section>
        {%endif%}
    </article>
</body>
</html>

suorganizer/organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{%block title%}
{{block.supper}}-Create Startup
{%endblock%}
{%block content%}
<div></div>
<form action="{%url'organizer_startup_create'%}" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Create Startup</button>
</form>
<div></div>
{%endblock%}

suorganizer/organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %} 
    {% blocktitle %}
    {{ block.super }} - {{ tag.name|title }}
    {% endblock %}
    {% block content%}
    <h2>Startup List</h2>
    <a href="{%url'blog_post_create'%}">Create New Startup</a>
    <ul>
        {% for startup in startup_list%}
        <li><a href="{{startup.get_absolute_url}}">{{startup.name}}</a></li>
        {%empty%}
        <li>No startups found</li>
        {% endfor%}
    </ul>
    {% endblock %}

suorganizer/organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{%block title%}
{{ block.super }} -Delete Tag
{%endblock%}

{%block content%}
<div>
</div>
<form action="{{tag.get_delete_url}}" method="post">
    {% csrf_token %}
    <p>
        Are you sure you want to delete tag {{tag.name}}?
    </p>
    <a href="{{tag.get_absolute_url}}">
        Cancel
    </a>
    <button type="submit">Delete Tag</button>
</form>
{%endblock%}

suorganizer/organizer/templates/organizer/tag_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{tag.name|title}}</h1>
    {% if tag.startup_set%}
    <section>      
        <h3>startup{{tag.startup_set.count|pluralize}}</h3>
        <p>The tag is associated with {{tag.startup_set.count}} startup{{tag.startup.all|length|pluralize}}</p>
        <ul>
            {% for startup in tag.startup_set.all%}
            <li><a href="{{startup.get_absolute_url}}">{{startup.name}}</a>
            </li>
            {% endfor %}
        </ul>
    </section>
        {% endif %}

    {% if tag.blog_posts%}
    <section>
        <h3>Blog post{{tag.blog_posts.count|pluralize}}</h3>
        <ul>
            {% for post in tag.blog_posts.all%}
            <li><a href="{{post.get_absolute_url}}">{{post.title|title}}</a></li>
            {% endfor%}
        </ul>
    </section>
    {% endif%}
    {% if not tag.starup_set.all and not tag.blog_posts.all%}
    <p>This tag is not related to any content.</p>
    {%endif%}
</body>
</html>

suorganizer/organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html"%}

{% block title%}
{{ block.super }} - create Tag
{% endblock %}

{% block content%}
<div>

</div>
<form action="{%url 'organizer_tag_create'%}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">
        create tag
    </button>
</form>
<div>
    
</div>
{%endblock%}










 <!-- {{ form.non_field_errors }}
    {{ form.name.errors }}
    <p>   
        {{ form.name.label }}
        {{ form.name }}
    </p>

    {{ form.slug.errors }}
    <p>
        {{ form.slug.label }}
        {{ form.slug }}
        <span class="helptext">{{ form.slug.help_text }}</span>
    </p>
    <button type="submit">create tag</button> -->


<!-- {%if form.slug.errors%}
    <ul>
        {%for error in form.slug.errors%}
        <li>{{error}}</li>
        {%endfor%}
    </ul>
    {%endif%} -->
    <!-- {%if form.name.errors%}
    <ul>
        {%for error in form.name.errors%}
        <li><em>{{error}}</em></li>
        {%endfor%}
    </ul>
    {%endif%} -->
    <!-- {%if form.non_field_errors%}
    <ul>
        {%for error in form.non_field_errors%}
        <li><em>{{error}}</em></li>
        {%endfor%}
    </ul>
    {%endif%} -->
    <!-- {%if form.slug.value%}
    <input type="text"id ="id_slug" name="slug"
    value="{{form.slug.value}}" maxlength="31">
    {%else%}
    <input type="text"id ="id_slug" name="slug" maxlength="31">
    {%endif%} -->
    <!-- {%if form.name.value%}
    <input type="text"id ="id_name" name="name"
    value="{{form.name.value}}" maxlength="31">
    {%else%}
    <input type="text"id ="id_name" name="name" maxlength="31">
    {%endif%} -->

suorganizer/organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{%block title%}
{{ block.super }} -Update Tag
{% endblock %}

{% block content %}
<div>
</div>
<form action="{{tag.get_update_url}}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update Tag</button>
</form>
<div>

</div>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organiser.html" %}
    {% block title%}
    {{block.super}}-Tag List
    {% endblock %}

    {% block content %}
    <h2>Tag List</h2>
    <div>
        <a href="{%url'organizer_tag_create'%}">Create New Tag</a>
    </div>
    <ul>
        {% for tag in tag_list%}
        <li><a href="{{tag.get_absolute_url}}">{{tag.name|title}}</a></li>
        {% empty%}
        <li><em>There are currently no Tags available.</em></li>
        {% endfor %}
    </ul>
    {% endblock %}
   